version: '2'
services:
  vcon-web:
    container_name: vcon-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_HOME=/vcon
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      DATABASE_URL: 'mysql2://root:toy_labo_vcon_2019@vcon-db:3306'
      TWITTER_API_KEY: "mMYWz7APXf1z3Eg9ikkiNXmQW"
      TWITTER_API_SECRET: "2M2Q1vRLNj4iiDjsPeOFGdaWevuJqcw995bqZFbiT6Ji3WGLN7"
      WEBHOOK_URL: "https://hooks.slack.com/services/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"
      RECAPTCHA_SITE_KEY: "6Lc-g6AUAAAAAGR2Iviy6LINUgAu47I7Q1qLnpxc"
      RECAPTCHA_SECRET_KEY: "6Lc-g6AUAAAAAJ0MF_Ro1zWBH_IDdNrFUThaP22l"
    command: rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/vcon
    ports:
      - "3000:3000"
    links:
      - vcon-db
    depends_on:
      - vcon-db
  vcon-db:
    container_name: vcon-db
    image: mysql:8.0.15
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default_authentication_plugin=mysql_native_password
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: toy_labo_vcon_2019
    ports:
      - "3307:3306"